// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourceGenerator.Metaprogramming
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EqualsTemplate : BaseTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\r\n{\r\n    public partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            this.Write("\r\n    {\r\n        public override bool Equals(object other)\r\n        {\r\n          " +
                    "  if(other is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLower()));
            this.Write(")\r\n            {\r\n                return ");
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyName));
            this.Write(".Equals(");
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName.ToLower()));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyName));
            this.Write(");\r\n            }\r\n\r\n            return false;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
